listen_port: 8080
ai_url: http://localhost:5000
storage_path: ./data
jwt_secret: "123456"

mysql:
  addr: localhost:3306
  user: root
  password: deepkw_lipread
  database: jcz

redis:
  addr: localhost:6379
  password: "123"